[workspace]
members = [
    "crates/pilgrim_core",
    "crates/pilgrim_handshake",
    "crates/pilgrim_bridge",
    "crates/amethyst_aegis",
    "crates/amethyst_invariants",
    "piano"
]

resolver = "2"
