[package]
name = "pilgrim_bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
pilgrim_handshake = { path = "../pilgrim_handshake" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

tiny_http = "0.12"
base64 = "0.22"
sha2 = "0.10"
hex = "0.4"
