[package]
name = "pilgrim_console"
version = "0.1.0"
edition = "2021"

[dependencies]
pilgrim_core = { path = "../pilgrim_core" }
pilgrim_identity = { path = "../pilgrim_identity" }
pilgrim_mandate = { path = "../pilgrim_mandate" }
