[package]
name = "pilgrim_core"
version = "0.1.0"
edition = "2021"

[dependencies]
pilgrim_handshake = { path = "../pilgrim_handshake" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

sha2 = "0.10"
hex = "0.4"
thiserror = "1"
