[package]
name = "pilgrim_sentinel"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pilgrim_dre = { path = "../pilgrim_dre" }
sha2 = "0.10"
thiserror = "1"
