[package]
name = "dre_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
pilgrim_sentinel = { path = "../pilgrim_sentinel" }
pilgrim_dre = { path = "../pilgrim_dre" }

serde = { version = "1.0", features = ["derive"] }
